version: 0.2

phases:
  build:
    commands:
      - mvn -B -f test-main -DskipTests clean install
      - mvn install -PTestRunner -f test-main/test-auto -Dcucumber.filter.tags="@rest and @sanity"

artifacts:
  files:
    - test-main/test-auto/target/**/*.json
    - test-main/test-auto/log/*
    - test-main/test-auto/reports/*

  discard-paths: yes
