version: "3.1"
services:
  testproject-agent:
    image: testproject/agent:latest
    container_name: testproject-agent
    volumes:
      - /var/tmp/testproject:/var/testproject/agent
    depends_on:
      - chrome
      - firefox
    environment:
      TP_API_KEY: "1ldUaKmikpVwj24Yu3XJ82QolwAH9JYSCxDSis9teQM1"
      TP_SDK_PORT: "8686"             # Agent will listen on port 8686 for SDK connections
      CHROME: "chrome:4444"           # Address for Agent to communicate with Chrome browser
      CHROME_EXT: "13.233.237.241:5555"    # Address for accessing the Chrome Selenium server
      FIREFOX: "firefox:4444"         # Address for Agent to communicate with Firefox browser
      FIREFOX_EXT: "13.233.237.241:5556"   # Address for accessing the Firefox Selenium server
    ports:
      - "8585:8585"
      - "8686:8686"                     # Expose port for SDK<->Agent communication
    chrome:
      image: selenium/standalone-chrome
      volumes:
        - /dev/shm:/dev/shm
      ports:
        - "5555:4444"                     # Expose Selenium on port 5555
    firefox:
      image: selenium/standalone-firefox
      volumes:
        - /dev/shm:/dev/shm
      ports:
        - "5556:4444"                     # Expose Selenium on port 5556